name: Coverage Report

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run coverage reporter
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: /coverage/lcov.info